version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taiga-nginx
    ports:
      - '44556:80'
    networks:
      - taiga-network

networks:
  taiga-network:
    driver: bridge
