version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taiga-nginx
    ports:
      - '65432:80'
    networks:
      - taiga-network
    # Remove the volume mount that was causing issues
    # volumes:
    #   - './nginx.conf:/etc/nginx/nginx.conf:ro'

# Rest of your compose file...
